### ISSUE TITLE
Icon for wishlist is green like visited

### ISSUE THREAD

**Issue by doc75** [ripienaar/travlrmap#54]
To avoid confusion, it would be good to have wishlist icon in orange like on travels.devco.net.
I tried on the site, but I do not have the exact RGB used to get the same orange ;-(

**Comment by ripienaar** [comment]
yeah - bit annoying, thats the defaults from the site I got them and that site was too annoying to try and automate different sets :)

I believe its #ffa500 on my side

**Comment by doc75** [comment]
Yes, I confirm that the color code is correct.
Do you mind if I replace just this one through a PR ?

**Comment by ripienaar** [comment]
yeah go ahead

**Comment by ripienaar** [comment]
thanks :)
