### ISSUE TITLE
Passenger 5.0.28, CentOS 7

### ISSUE THREAD

**Issue by flare04** [ripienaar/travlrmap#62]
Hi,

I've come across an issue with version 1.5.1, running on CentOS 7, Apache 2.4, ruby 2.2, and passenger 5.0.28.

After running `bundle update`, I then ran `bundle exec rackup` and browsed to http://<fqdn>:9292/ I'm greeted with an error message and the following backtrace:-

bundle exec rackup
[2016-06-05 09:42:21] INFO  WEBrick 1.3.1
[2016-06-05 09:42:21] INFO  ruby 2.0.0 (2014-11-13) [x86_64-linux]
[2016-06-05 09:42:21] INFO  WEBrick::HTTPServer#start: pid=14275 port=9292
2016-06-05 09:42:40 - NoMethodError - undefined method `intern' for nil:NilClass:
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/point.rb:90:in`from_hash'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/point.rb:9:in `initialize'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:151:in`new'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:151:in `block in points_from_data'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:150:in`each'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:150:in `points_from_data'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:157:in`block in load_directory'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:156:in `each'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:156:in`load_directory'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:132:in `block in load_points'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:125:in`each'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:125:in `load_points'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:127:in`block in load_points'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:125:in `each'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/points.rb:125:in`load_points'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/sinatra_app.rb:84:in `load_map'
    /usr/local/share/gems/gems/travlrmap-1.5.1/lib/travlrmap/sinatra_app.rb:118:in`block in class:SinatraApp'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in`block in compile!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in`block (3 levels) in route!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in`block (2 levels) in route!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in`catch'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in`block in route!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in`route!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`block in invoke'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`invoke'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in`block in call!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in`catch'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in`call!'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in`call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in`call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in`call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in`call'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in`call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/lint.rb:37:in`call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in`call'
    /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/chunked.rb:43:in`call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /usr/local/share/gems/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in`service'
    /usr/share/ruby/webrick/httpserver.rb:138:in `service'
    /usr/share/ruby/webrick/httpserver.rb:94:in`run'
    /usr/share/ruby/webrick/server.rb:295:in `block in start_thread'
124.170.248.192 - - [05/Jun/2016 09:42:40] "GET / HTTP/1.1" 500 178191 0.0754
124.170.248.192 - - [05/Jun/2016 09:42:41] "GET /**sinatra**/500.png HTTP/1.1" 304 - 0.0224
124.170.248.192 - - [05/Jun/2016 09:42:42] "GET /favicon.ico HTTP/1.1" 200 1406 0.0040

Note mod_passenger, passenger require rack 1.6.4.

Regards

**Comment by ripienaar** [comment]
This appear to be related to corrupt/bad data in your yaml files

Can you post those somewhere? 

(Am away for a week so responses are slow)

**Comment by flare04** [comment]
Hi,

Thanks for pointing me int he correct place, it’s all good now.  Was missing lat entry for a visit.

Thanks again

**Comment by ripienaar** [comment]
great, i need to improve error reporting around that :(
